### ISSUE TITLE
broken code should occur in branches

### ISSUE THREAD

**Issue by tdhock** [vrunge/gfpop#5]
hey @vrunge 
```
DANGER : code broken in August in preparation for big update!
```
suggestion: rather than always pushing commits to master, I would suggest creating a new branch and pushing to that, in order to leave master in a working state. https://guides.github.com/introduction/flow/

after you test your new commits (maybe using CI, e.g. https://docs.travis-ci.com/user/languages/r/ ) then you would merge them into master, using a pull request https://help.github.com/en/articles/about-pull-requests

**Comment by vrunge** [comment]
Hi @tdhock 
You're right ! It's because I am afraid of the merging step, afraid to lose some parts of the code...
I will try this approach for the next big updates.

**Comment by tdhock** [comment]
typically there are no merge conflicts when you have only one branch which is different from master.

conflicts happen if you have multiple people working on different (incompatible) branches.

anyways if there is a merge conflict the code is not lost -- you get to choose which version of the conflicted code to use.
